### ISSUE TITLE
Merge xdg desktop package with upsteam gentoo

### ISSUE THREAD

**Issue by marcthe12** [fosero/flatpak-overlay#36]
Upstream gentoo has already added xdg-desktop-portal and xdg-desktop-portal-kde.
Should we keep copies of upstream or just remove it.
Another question is xdg-desktop-portal-gtk. Should try to get into mainline gentoo.

**Comment by fosero** [comment]
I am not sure why the KDE team decided to package them, as they are not very useful without Flatpak afaik. And there still is little movement to bring Flatpak itself to the main tree.

I am keeping the main portal in this tree for now, because I am not sure how well it will be maintained. As for the GTK portal, the Gentoo GNOME team does not have the time to keep up with the regular GNOME releases, I doubt they need an used portal package in the tree to maintain as well.

I did remove the kde portal in favor of Gentoo, as it was outdated and the guy who was maintaining them seems to have lost interest.

**Comment by marcthe12** [comment]
ok. We should keep an eye out on xdg-desktop-portal.

**Comment by realnc** [comment]
> I am not sure why the KDE team decided to package them, as they are not very useful without Flatpak afaik.

Firefox uses it when `GTK_USE_PORTAL=1` is set in the environment. Maybe other applications use it as well, not sure.

https://wiki.archlinux.org/index.php/Firefox#KDE/GNOME_integration

**Comment by fosero** [comment]
I did not know that, thanks. I guess it makes sense from the standpoint of a cross-platform app developer. It is 1 less api to target and it right-away works in sandboxes.
