### ISSUE TITLE
sys-fs/libostree conflicts with dev-util/ostree

### ISSUE THREAD

**Issue by kryptt** [fosero/flatpak-overlay#53]
The package you maintain here collides with dev-util/ostree in mainline; I'm guessing renaming this ebuild might make sense so they become the same on?

**Comment by fosero** [comment]
Been like that for a long time, I updated the naming in accordance with the upstream rename. This was never a problem before because of the unused/outdated ostree package in the main Gentoo tree. Recently that has been updated and flatpak has been added to the main tree. That makes this overlay eol, I recently added a move to make the ostree transition smooth (4bf9a7815ca9361f86459c8a8e9bc403e3721704).
